name: Semver release checks

on:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  semver-checks:

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4 
      - uses: obi1kenobi/cargo-semver-checks-action@v2
