[package]
name = "chorus-postgres"
version = "0.1.0"
edition = "2024"

[dependencies]
chorus = { version = "0.19.0", path = "../chorus", features = [
    "backend",
], default-features = false }
sqlx = "0.8.3"
sqlx-pg-uint = { version = "0.9.0", features = ["serde"] }
